"""empty message

Revision ID: 394ffd17afa8
Revises: 46894bfaef11
Create Date: 2014-07-22 19:06:57.321418

"""

# revision identifiers, used by Alembic.
revision = '394ffd17afa8'
down_revision = '46894bfaef11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'user_ip_addr_key', 'user')
    op.drop_index('user_ip_addr_key', table_name='user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_ip_addr_key', 'user', ['ip_addr'], unique=True)
    op.create_unique_constraint(u'user_ip_addr_key', 'user', ['ip_addr'])
    ### end Alembic commands ###
