"""empty message

Revision ID: 46894bfaef11
Revises: None
Create Date: 2014-07-20 09:29:07.329399

"""

# revision identifiers, used by Alembic.
revision = '46894bfaef11'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
